"""OpenRouter client for Rendervous.

Uses the dedicated image endpoints: GET /api/v1/images/models to list
image-generation models, POST /api/v1/images to generate (response image is
at data[0].b64_json). Reference images (img2img) go in input_references.

Model list + prices come from the bundled static catalog
(server/models_catalog.json), regenerated by scripts/refresh_models.py — no
live OpenRouter call on listing. Users bring their own API key: pass api_key
per call; we never store it. When omitted we fall back to the
OPENROUTER_API_KEY env var.
"""

import base64
import json
import math
import os
import re

import requests

API_URL = "https://openrouter.ai/api/v1"
DEFAULT_MODEL = "google/gemini-3.1-flash-image"
RECOMMENDED = {
    "bytedance-seed/seedream-5-0-pro",
    "google/gemini-2.5-flash-image",
    "google/gemini-3.1-flash-image",
}
CATALOG_PATH = os.path.join(os.path.dirname(__file__), "models_catalog.json")


class OpenRouterError(Exception):
    """Raised when OpenRouter returns a non-200 or a malformed response."""


# Aspect ratios the OpenRouter images endpoint accepts (first wins ties).
ASPECT_RATIOS = (
    "1:1",
    "16:9",
    "9:16",
    "4:3",
    "3:4",
    "3:2",
    "2:3",
    "4:5",
    "5:4",
    "1:2",
    "2:1",
    "1:4",
    "4:1",
    "1:8",
    "8:1",
    "9:21",
    "21:9",
)


def _ratio_value(r):
    """Log of a ratio string's w/h. Malformed strings count as 1:1."""
    try:
        w, h = r.split(":")
        return math.log(float(w) / float(h))
    except (ValueError, ZeroDivisionError):
        return 0.0


def closest_aspect_ratio(width, height):
    """Nearest supported ratio to width/height by log-distance.

    Log-distance keeps 9:16 and 16:9 equal-and-opposite from 1:1. Ties go to
    the earliest entry. Used to derive the output ratio from the reference
    image server-side so the API param is always set, not left to a prompt
    hint the model may ignore.
    """
    return closest_ratio_to(f"{width}:{height}", ASPECT_RATIOS)


def closest_ratio_to(target, ratios):
    """Nearest ratio to `target` ("w:h") from `ratios` by log-distance.

    Ties go to the earliest entry of `ratios`.
    """
    return min(ratios, key=lambda r: abs(_ratio_value(target) - _ratio_value(r)))


def _accepted_ratios(error_message):
    """Parse provider-rejected-parameter error messages like

    "No provider for X supports ... aspect_ratio: not supported. Accepted:
    1:1, 16:9, ... | Google: aspect_ratio: not supported. Accepted: ..."

    Returns the intersection of every "Accepted:" list in the message (a
    retry must satisfy all rejecting providers), or [] when the message
    doesn't match the pattern. Falls back to the first list if the
    intersection is empty (providers disagreeing is better than nothing).
    """
    lists = []
    for chunk in re.findall(r"Accepted:\s*([\d.,:\s]+)", error_message):
        ratios = re.findall(r"\d+(?:\.\d+)?:\d+(?:\.\d+)?", chunk)
        if ratios:
            lists.append(ratios)
    if not lists:
        return []
    common = set(lists[0]).intersection(*lists[1:])
    if common:
        return [r for r in lists[0] if r in common]
    return lists[0]


def resolve_key(api_key):
    """Per-request key wins; env var is the fallback. Never persisted."""
    if api_key:
        return api_key
    return os.environ.get("OPENROUTER_API_KEY", "")


def _to_int(v):
    """Coerce job-param values (may be floats/strings from JSON) to int or None."""
    try:
        return int(v)
    except (TypeError, ValueError):
        return None


def list_models():
    """Image-generation models from the bundled static catalog.

    Returns list of {id, name, recommended, input_price, price_usd,
    price_unit, context_length}. price_usd/price_unit come from the
    dedicated Image Models API (scripts/refresh_models.py): the resolved
    output_image line in its native unit — "image" (USD per image),
    "megapixel" (USD per megapixel), "token" (USD per token). Models with
    no published output price get price_usd=null (clients show "—").
    Sorted by recommended first, then id.
    """
    try:
        with open(CATALOG_PATH) as f:
            catalog = json.load(f)["models"]
    except (OSError, ValueError, KeyError) as e:
        # Bundled file missing/corrupt is a deployment error, not a runtime
        # one; fail loud so it's noticed instead of serving an empty list.
        raise OpenRouterError(f"models catalog unavailable: {e}") from e
    models = [
        {
            "id": m["id"],
            "name": m["name"],
            "recommended": m["id"] in RECOMMENDED,
            "input_price": None,
            "price_usd": m.get("price_usd"),
            "price_unit": m.get("price_unit"),
            "context_length": None,
        }
        for m in catalog
    ]
    models.sort(key=lambda x: (not x["recommended"], x["id"]))
    return models


def generate(
    model,
    prompt,
    image_url=None,
    api_key=None,
    seed=None,
    aspect_ratio=None,
) -> bytes:
    """Call the dedicated OpenRouter image endpoint (POST /api/v1/images).

    image_url: optional data URL of the reference image (img2img, mapped to
    input_references), or ""/None for pure text-to-image.
    aspect_ratio: one of the supported ratios (e.g. "16:9"), or "auto".
    Returns the decoded output PNG bytes (data[0].b64_json).
    """
    key = resolve_key(api_key)
    if not key:
        raise OpenRouterError(
            "No OpenRouter API key configured. Set OPENROUTER_API_KEY or pass "
            "your key (X-OpenRouter-Key header / api_key field). Your key is "
            "never stored."
        )

    body = {
        "model": model or DEFAULT_MODEL,
        "prompt": prompt,
        "n": 1,
        "output_format": "png",
    }
    if aspect_ratio:
        body["aspect_ratio"] = aspect_ratio
    if image_url:
        body["input_references"] = [
            {"type": "image_url", "image_url": {"url": image_url}}
        ]
    seed_i = _to_int(seed)
    if seed_i is not None and seed_i != -1:
        body["seed"] = seed_i

    resp = _post_images(key, body)
    if resp.status_code == 400 and body.get("aspect_ratio"):
        # Providers reject out-of-subset ratios with a 400 listing what they
        # accept. Snap to the nearest accepted ratio and retry once.
        accepted = _accepted_ratios(_error_detail(resp))
        if accepted and body["aspect_ratio"] not in accepted:
            body["aspect_ratio"] = closest_ratio_to(body["aspect_ratio"], accepted)
            resp = _post_images(key, body)
    if resp.status_code != 200:
        raise OpenRouterError(
            f"OpenRouter error {resp.status_code}: {_error_detail(resp)}"
        )

    data = resp.json()
    try:
        b64 = data["data"][0]["b64_json"]
    except (KeyError, IndexError, TypeError) as e:
        raise OpenRouterError(f"Unexpected OpenRouter response: {e}") from e
    return base64.b64decode(b64)


def _post_images(key, body):
    """POST one image-generation request; returns the raw response."""
    return requests.post(
        f"{API_URL}/images",
        headers={
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
        },
        json=body,
        timeout=300,
    )


def _error_detail(resp):
    """Best-effort human-readable error message from a non-200 response."""
    try:
        return resp.json().get("error", {}).get("message", resp.text[:400])
    except Exception:
        return resp.text[:400]
