"""OpenRouter client for Rendervous.

Uses the dedicated image endpoints: GET /api/v1/images/models to list
image-generation models, POST /api/v1/images to generate (response image is
at data[0].b64_json). Reference images (img2img) go in input_references.

Model list + prices come from the bundled static catalog
(server/models_catalog.json), regenerated by scripts/refresh_models.py — no
live OpenRouter call on listing. Users bring their own API key: pass api_key
per call; we never store it. When omitted we fall back to the
OPENROUTER_API_KEY env var.
"""

import base64
import json
import os

import requests

API_URL = "https://openrouter.ai/api/v1"
DEFAULT_MODEL = "bytedance-seed/seedream-5-0-pro"
RECOMMENDED = {
    "bytedance-seed/seedream-5-0-pro",
    "google/gemini-2.5-flash-image",
    "google/gemini-3.1-flash-image",
}
CATALOG_PATH = os.path.join(os.path.dirname(__file__), "models_catalog.json")


class OpenRouterError(Exception):
    """Raised when OpenRouter returns a non-200 or a malformed response."""


def resolve_key(api_key):
    """Per-request key wins; env var is the fallback. Never persisted."""
    if api_key:
        return api_key
    return os.environ.get("OPENROUTER_API_KEY", "")


def _to_int(v):
    """Coerce job-param values (may be floats/strings from JSON) to int or None."""
    try:
        return int(v)
    except (TypeError, ValueError):
        return None


def list_models():
    """Image-generation models from the bundled static catalog.

    Returns list of {id, name, recommended, input_price, price_usd,
    price_unit, context_length}. price_usd/price_unit come from the
    dedicated Image Models API (scripts/refresh_models.py): the resolved
    output_image line in its native unit — "image" (USD per image),
    "megapixel" (USD per megapixel), "token" (USD per token). Models with
    no published output price get price_usd=null (clients show "—").
    Sorted by recommended first, then id.
    """
    try:
        with open(CATALOG_PATH) as f:
            catalog = json.load(f)["models"]
    except (OSError, ValueError, KeyError) as e:
        # Bundled file missing/corrupt is a deployment error, not a runtime
        # one; fail loud so it's noticed instead of serving an empty list.
        raise OpenRouterError(f"models catalog unavailable: {e}") from e
    models = [
        {
            "id": m["id"],
            "name": m["name"],
            "recommended": m["id"] in RECOMMENDED,
            "input_price": None,
            "price_usd": m.get("price_usd"),
            "price_unit": m.get("price_unit"),
            "context_length": None,
        }
        for m in catalog
    ]
    models.sort(key=lambda x: (not x["recommended"], x["id"]))
    return models


def generate(
    model,
    prompt,
    image_url=None,
    api_key=None,
    seed=None,
    aspect_ratio=None,
) -> bytes:
    """Call the dedicated OpenRouter image endpoint (POST /api/v1/images).

    image_url: optional data URL of the reference image (img2img, mapped to
    input_references), or ""/None for pure text-to-image.
    aspect_ratio: one of the supported ratios (e.g. "16:9"), or "auto".
    Returns the decoded output PNG bytes (data[0].b64_json).
    """
    key = resolve_key(api_key)
    if not key:
        raise OpenRouterError(
            "No OpenRouter API key configured. Set OPENROUTER_API_KEY or pass "
            "your key (X-OpenRouter-Key header / api_key field). Your key is "
            "never stored."
        )

    body = {
        "model": model or DEFAULT_MODEL,
        "prompt": prompt,
        "n": 1,
        "output_format": "png",
    }
    if aspect_ratio:
        body["aspect_ratio"] = aspect_ratio
    if image_url:
        body["input_references"] = [
            {"type": "image_url", "image_url": {"url": image_url}}
        ]
    seed_i = _to_int(seed)
    if seed_i is not None and seed_i != -1:
        body["seed"] = seed_i

    resp = requests.post(
        f"{API_URL}/images",
        headers={
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
        },
        json=body,
        timeout=300,
    )
    if resp.status_code != 200:
        detail = ""
        try:
            detail = resp.json().get("error", {}).get("message", resp.text[:400])
        except Exception:
            detail = resp.text[:400]
        raise OpenRouterError(f"OpenRouter error {resp.status_code}: {detail}")

    data = resp.json()
    try:
        b64 = data["data"][0]["b64_json"]
    except (KeyError, IndexError, TypeError) as e:
        raise OpenRouterError(f"Unexpected OpenRouter response: {e}") from e
    return base64.b64decode(b64)
